### ISSUE TITLE
Stats wrapping on another line

### ISSUE THREAD

**Issue by SOLiNARY** [LeoMavri/torn-stats-central-script#21]
stats wrapping on another line.
adding `.tsc-faction-spy { text-wrap: nowrap; }` fixes it.
example from faction page.

![image](https://github.com/LeoMavri/TSC-Companion/assets/3579801/0270053d-d44b-4b62-baf6-6f25cafb5f5b)

**Comment by LeoMavri** [comment]
Fixed in d000b15
